# netlify.toml

[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  node_version = "18" # You can change this to "20" if you prefer Node.js 20

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
